<?php

/** @var \App\DataSource\User\UserRecord $loggedUser */
/** @var string $csrfToken */

?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <title><?= $this->e($title) ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="/logo.png">
    <link href="/bootstrap-4.5.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="text-center">
<?= $this->section('content') ?>
</div>
</body>
</html>
