<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Event;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $game_id int(10,0) unsigned NOT NULL
 * @property mixed $type enum(5) NOT NULL
 * @property mixed $player_id int(10,0) unsigned
 * @property mixed $word varchar(50)
 */
class EventRow extends Row
{
    protected $cols = [
        'id' => null,
        'game_id' => null,
        'type' => null,
        'player_id' => 0,
        'word' => 'NULL',
    ];
}
