<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Game;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $code char(8) NOT NULL
 * @property mixed $creator_id int(10,0) unsigned NOT NULL
 */
trait GameFields
{
}
