<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Game;

use Atlas\Table\Table;

/**
 * @method GameRow|null fetchRow($primaryVal)
 * @method GameRow[] fetchRows(array $primaryVals)
 * @method GameTableSelect select(array $whereEquals = [])
 * @method GameRow newRow(array $cols = [])
 * @method GameRow newSelectedRow(array $cols)
 */
class GameTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'games';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'code' => array (
  'name' => 'code',
  'type' => 'char',
  'size' => 8,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'creator_id' => array (
  'name' => 'creator_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'code',
        'creator_id',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'code' => null,
        'creator_id' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
