<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\User;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $username varchar(32) NOT NULL
 * @property mixed $password_sha512 varchar(128) NOT NULL
 * @property mixed $password_salt varchar(16) NOT NULL
 * @property mixed $email varchar(100) NOT NULL
 */
trait UserFields
{
}
