<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Player;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $game_id int(10,0) unsigned NOT NULL
 * @property mixed $player_id int(10,0) unsigned NOT NULL
 * @property mixed $active tinyint(3,0) NOT NULL
 */
class PlayerRow extends Row
{
    protected $cols = [
        'id' => null,
        'game_id' => null,
        'player_id' => null,
        'active' => null,
    ];
}
